name: "Publish"

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 20 * * *'
  workflow_dispatch:

jobs:
  determine-actions-cli-version:
    name: Determine CLI version installed in Actions
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.cliversion.outputs.v }}
    steps:
    - id: downloadcli
      uses: github/codeql-action/init@v2
    - id: cliversion
      run: |
        echo "::set-output name=v::"$(${{ steps.downloadcli.outputs.codeql-path }} version -q)

  build-test-and-publish-packs:
    name: Build, Test and Publish CodeQL Packs
    runs-on: ubuntu-latest
    needs: determine-actions-cli-version

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build, Test and Publish
      env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
         echo ${{ needs.determine-actions-cli-version.outputs.version }}
         gh extensions install github/gh-codeql
         gh extensions install zbazztian/gh-tailor
         gh codeql download v${{ needs.determine-actions-cli-version.outputs.version }}
         gh codeql set-version v${{ needs.determine-actions-cli-version.outputs.version }}
         ./publish "${{ matrix.language }}"
